/**
 * Created by robertzzy on 09/07/16.
 */

export const EXERCISE_SEARCH_RESULT_RECEIVED = 'EXERCISE_SEARCH_RESULT_RECEIVED';

export const EQUIPMENT_SEARCH_RESULT_RECEIVED = 'EQUIPMENT_SEARCH_RESULT_RECEIVED';

export const MUSCLE_SEARCH_RESULT_RECEIVED = 'MUSCLE_SEARCH_RESULT_RECEIVED';

export const MUSCLE_GROUP_SEARCH_RESULT_RECEIVED = 'MUSCLE_GROUP_SEARCH_RESULT_RECEIVED';

export const GET_ALL_MUSCLES_RECEIVED = 'GET_ALL_MUSCLES_RECEIVED';

export const GET_ALL_EQUIPMENT_RECEIVED = 'GET_ALL_EQUIPMENT_RECEIVED';

export const SELECTED_MODEL = 'SELECTED_MODEL';

export const CREATE_ENTRY_REQUEST_SENT = 'CREATE_ENTRY_REQUEST_SENT';

export const CREATE_ENTRY_RESULT_ACKNOWLEDGED = 'CREATE_ENTRY_RESULT_ACKNOWLEDGED';

export const ENTRY_CREATED = 'ENTRY_CREATED';

export const ADD_CREATE_ENTRY_FIELD = 'ADD_CREATE_ENTRY_FIELD';