/**
 * Created by robertzzy on 09/07/16.
 */

export const SEARCH_EXERCISE = 'SEARCH_EXERCISE';

export const EXERCISE_SEARCH_RESULT_RECEIVED = 'EXERCISE_SEARCH_RESULT_RECEIVED';


export const SEARCH_EQUIPMENT = 'SEARCH_EQUIPMENT';

export const EQUIPMENT_SEARCH_RESULT_RECEIVED = 'EQUIPMENT_SEARCH_RESULT_RECEIVED';


export const SEARCH_MUSCLE = 'SEARCH_MUSCLE';

export const MUSCLE_SEARCH_RESULT_RECEIVED = 'MUSCLE_SEARCH_RESULT_RECEIVED';


export const SEARCH_MUSCLE_GROUP = 'SEARCH_MUSCLE_GROUP';

export const MUSCLE_GROUP_SEARCH_RESULT_RECEIVED = 'MUSCLE_GROUP_SEARCH_RESULT_RECEIVED';

export const GET_ALL_MUSCLES = 'GET_ALL_MUSCLES';

export const GET_ALL_EQUIPMENT = 'GET_ALL_EQUIPMENT';

export const GET_ALL_MUSCLES_RECEIVED = 'GET_ALL_MUSCLES_RECEIVED';

export const GET_ALL_EQUIPMENT_RECEIVED = 'GET_ALL_EQUIPMENT_RECEIVED';

export const CREATE_EXERCISE = 'CREATE_EXERCISE';

export const CREATE_EQUIPMENT = 'CREATE_EQUIPMENT';

export const CREATE_MUSCLE = 'CREATE_MUSCLE';

export const CREATE_MUSCLE_GROUP = 'CREATE_MUSCLE_GROUP';