/**
 * Created by robertzzy on 16/07/16.
 */
export const CREATE_ENTRY_STATE_PENDING = 'CREATE_ENTRY_STATE_PENDING';
export const CREATE_ENTRY_STATE_RECEIVED = 'CREATE_ENTRY_STATE_RECEIVED';
export const CREATE_ENTRY_STATE_CREATE = 'CREATE_ENTRY_STATE_CREATE';