/**
 * Created by robertzzy on 16/07/16.
 */
export const CREATE_RESOURCE_STATE_PENDING = 'CREATE_RESOURCE_STATE_PENDING';
export const CREATE_RESOURCE_STATE_RECEIVED = 'CREATE_RESOURCE_STATE_RECEIVED';
export const CREATE_RESOURCE_STATE_IDLE = 'CREATE_RESOURCE_STATE_IDLE';