/**
 * Created by robertzzy on 03/08/16.
 */
export const UPDATE_RESOURCE_REQUIREMENT_PENDING = 'UPDATE_RESOURCE_REQUIREMENT_PENDING';
export const UPDATE_RESOURCE_REQUIREMENT_RECEIVED = 'UPDATE_RESOURCE_REQUIREMENT_RECEIVED';