/**
 * Created by robertzzy on 02/08/16.
 */
export const UPDATE_RESOURCE_STATE_PENDING = 'UPDATE_RESOURCE_STATE_PENDING';
export const UPDATE_RESOURCE_STATE_RECEIVED = 'UPDATE_RESOURCE_STATE_RECEIVED';
export const UPDATE_RESOURCE_STATE_IDLE = 'UPDATE_RESOURCE_STATE_IDLE';